# get_oc_assets.yml 

- name: Get the latest release
  uri:
    url: "{{ minishift_github_url }}/{{ openshift_repo }}/releases/latest"
  register: release

- name: Set release
  set_fact:
    assets_url: "{{ release.json.assets_url }}"

- name: Should have an assets_url
  assert:
    that: assets_url is defined

- name: debug
  debug:
    var: assets_url

- name: Get the list of assets
  uri:
    url: "{{ assets_url }}"
  register: assets

