# main.yml
---

- name: Install Docker machine driver
  include_tasks: "{{ ansible_os_family }}_driver.yml"

- name: Check if minishift binary exists
  stat:
    path: "{{ minishift_dest }}/minishift"
  register: minishift_client

- name: Get minishift assets
  include_tasks: get_ms_assets.yml

- name: Install minishift
  include_tasks: install_minishift.yml
  when: not minishift_client.stat.exists or minishift_force_install

- name: Remove existing minishift instance
  include_tasks: isrunning.yml

# Lately seems to always end with a non-zero return code, even on success
- name: Run minishift
  shell: "minishift start {{ minishift_start_options | join(' ') }} >/tmp/minishift.out 2>&1"
  environment:
    # Enable mounting /Users to the VM on OSX
    XHYVE_VIRTIO_9P: true
  ignore_errors: yes

- name: Grab the minishift output, stripping any special chars
  shell: cat /tmp/minishift.out | tr -dc '[:print:]\n\r' | grep -v '==='
  register: minishift_out

- name: Cleanup output file
  file:
    path: /tmp/minishift.out
    state: absent

- name: Check if oc binary exists
  stat:
    path: "{{ openshift_client_dest }}/oc"
  register: oc_client

- name: Copy latest oc client from ~/.minishift
  include_tasks: copy_oc_client.yml
  when: not oc_client.stat.exists or openshift_force_client_copy

- name: Switch the kube config context
  shell: "{{ openshift_client_dest }}/oc config use-context /$(minishift ip | tr . -):8443/developer"

- name: Give cluster-admin to developer
  include_tasks: grant_admin.yml

- name: Create objects
  include_tasks: create_objects.yml

- name: Add entry to /etc/hosts
  include_tasks: add_hostname.yml

- name: Show output
  debug:
    var: minishift_out.stdout_lines
